services:
  - type: web
    name: nycad-stock-trading
    runtime: java
    region: oregon
    plan: free
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/stock-trading-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILE
        value: prod
      - key: DATABASE_HOST
        fromDatabase:
          name: stock-trading-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: stock-trading-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: stock-trading-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: stock-trading-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: stock-trading-db
          property: password
    
databases:
  - name: stock-trading-db
    databaseName: stocktrading
    region: oregon
    plan: free
