server.port=${PORT:8080}
spring.profiles.active=${SPRING_PROFILE:prod}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.url=jdbc:${DATABASE_URL:postgresql://localhost:5432/stocktrading}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000